# KNN
It is one of the simplest ML Algorithms
Based on supervised learning
Also called as lazy learner algorithm since it just stores data and runs it on the go.
Uses distance formula.
Can be used for both continuos and categorical data so can be used for Regression as well as Classification.
Can also be used to replace missing values

In [3]:
from sklearn.datasets import load_wine
from sklearn.neighbors import KNeighborsClassifier
import pandas as pd
import numpy as np
wine= load_wine()
x=wine.data
col_names=wine.feature_names
target_names=wine.target_names
df=pd.DataFrame(data=x,columns=col_names)
print(wine.data.shape)
print(wine.data[:5])

(178, 13)
[[1.423e+01 1.710e+00 2.430e+00 1.560e+01 1.270e+02 2.800e+00 3.060e+00
  2.800e-01 2.290e+00 5.640e+00 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 1.120e+01 1.000e+02 2.650e+00 2.760e+00
  2.600e-01 1.280e+00 4.380e+00 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 1.860e+01 1.010e+02 2.800e+00 3.240e+00
  3.000e-01 2.810e+00 5.680e+00 1.030e+00 3.170e+00 1.185e+03]
 [1.437e+01 1.950e+00 2.500e+00 1.680e+01 1.130e+02 3.850e+00 3.490e+00
  2.400e-01 2.180e+00 7.800e+00 8.600e-01 3.450e+00 1.480e+03]
 [1.324e+01 2.590e+00 2.870e+00 2.100e+01 1.180e+02 2.800e+00 2.690e+00
  3.900e-01 1.820e+00 4.320e+00 1.040e+00 2.930e+00 7.350e+02]]


In [4]:
df.head()

alcohol  malic_acid   ash  alcalinity_of_ash  magnesium  total_phenols  \
0    14.23        1.71  2.43               15.6      127.0           2.80   
1    13.20        1.78  2.14               11.2      100.0           2.65   
2    13.16        2.36  2.67               18.6      101.0           2.80   
3    14.37        1.95  2.50               16.8      113.0           3.85   
4    13.24        2.59  2.87               21.0      118.0           2.80   

   flavanoids  nonflavanoid_phenols  proanthocyanins  color_intensity   hue  \
0        3.06                  0.28             2.29             5.64  1.04   
1        2.76                  0.26             1.28             4.38  1.05   
2        3.24                  0.30             2.81             5.68  1.03   
3        3.49                  0.24             2.18             7.80  0.86   
4        2.69                  0.39             1.82             4.32  1.04   

   od280/od315_of_diluted_wines  proline  
0                          3.92   1065.0  
1                          3.40   1050.0  
2                          3.17   1185.0  
3                          3.45   1480.0  
4                          2.93    735.0

In [5]:
# Here we need to normalize the values
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(wine.data,wine.target,test_size=0.3)

In [14]:
# K=5
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [15]:
from sklearn import metrics
print({'Accuarcy': metrics.accuracy_score(y_test,y_pred)})


{'Accuarcy': 0.7592592592592593}


In [19]:
# With Preprocessing
from sklearn import preprocessing 
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
scaler.fit(wine.data)
temp=scaler.fit_transform(wine.data)
print(temp)

[[0.84210526 0.1916996  0.57219251 ... 0.45528455 0.97069597 0.56134094]
 [0.57105263 0.2055336  0.4171123  ... 0.46341463 0.78021978 0.55064194]
 [0.56052632 0.3201581  0.70053476 ... 0.44715447 0.6959707  0.64693295]
 ...
 [0.58947368 0.69960474 0.48128342 ... 0.08943089 0.10622711 0.39728959]
 [0.56315789 0.36561265 0.54010695 ... 0.09756098 0.12820513 0.40085592]
 [0.81578947 0.66403162 0.73796791 ... 0.10569106 0.12087912 0.20114123]]


In [23]:
# Here we need to normalize the values and Split it again
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(temp,wine.target,test_size=0.3)

In [24]:
# K=5
knn=KNeighborsClassifier(n_neighbors=5)
knn.fit(x_train,y_train)
y_pred=knn.predict(x_test)

In [25]:
from sklearn import metrics
print({'Accuarcy': metrics.accuracy_score(y_test,y_pred)})


{'Accuarcy': 0.9444444444444444}
