## Background for NumPY
It is a multidimensional arrays libraries. 1D or 2D or nD.
### Why to use NumPy ?
Numpy uses fixed types instead of hetereogenous components of list.
5--> 101 --> converted to INT 32, you can specify in 2 bytes etc.
With lists, it used built-in INT of python which consists of Size, Reference COunt, Object Type and Object Value. So it comes down to 8 bytes. It is higher than numpy.

So key takeways:
1. Faster to read less bytes of memory
2. No type checking
3. Has contiguous memory
4. List has pointers pointing to data which are scattereed in memory
5. Our CPUs have SIMD vector processing units, so in continuous memory we can use it for faster computation
6. Effective Cache Unitlization in NumPy
7. In NumPy we can do more than lists
8. Allows itemwise computation

### Applications of NumPy
1. Maths (MATLAB replacement)
2. Plotting
3. Backend of Pandas, Connect 4, Digital Photography(PNG,JPEG)
4. Machine Learning -tensors

In [1]:
import numpy as np

## Basics

In [23]:
a=np.array([1,2,3],dtype='int16')
print(a)

[1 2 3]


In [101]:
b=np.array([[1,2,3,4],[3,4,5,6]])
b

array([[1, 2, 3, 4],
       [3, 4, 5, 6]])

In [103]:
# Create an empty array with 2 elements
np.empty(2) 

array([1., 1.])

In [104]:
# You can create an array with a range of elements:
np.arange(4)

array([0, 1, 2, 3])

In [105]:
# You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [106]:
# You can quickly sort the numbers in ascending order with:
np.sort(a)

array([[1, 2],
       [3, 5]])

In [ ]:
x=np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
# You can concatenate them with:

np.concatenate((x, y), axis=0)

ndarray.ndim will tell you the number of axes, or dimensions, of the array.

ndarray.size will tell you the total number of elements of the array. This is the product of the elements of the array’s shape.

ndarray.shape will display a tuple of integers that indicate the number of elements stored along each dimension of the array. If, for example, you have a 2-D array with 2 rows and 3 columns, the shape of your array is (2, 3).

In [25]:
# Get the dimension
a.ndim

1

In [26]:
b.ndim

2

In [27]:
# Get shape
a.shape

(3,)

In [28]:
b.shape

(2, 4)

In [29]:
# Get Type
a.dtype

dtype('int16')

In [30]:
b.dtype

dtype('int32')

In [32]:
# Get size
a.itemsize

2

In [34]:
#get total size - no of elements
# a.size
# a.size*a.itemsize
a.nbytes

6

Using arr.reshape() will give a new shape to an array without changing the data. Just remember that when you use the reshape method, the array you want to produce needs to have the same number of elements as the original array. If you start with an array with 12 elements, you’ll need to make sure that your new array also has a total of 12 elements.

In [111]:
k = b.reshape(4,2)
print(k)


[[1 2]
 [3 4]
 [3 4]
 [5 6]]


You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

Using np.newaxis will increase the dimensions of your array by one dimension when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [113]:
a2 = a[np.newaxis, :]
a2.shape


(1, 2, 2)

In [115]:
# You can use np.expand_dims to add an axis at index position 1 with:

b = np.expand_dims(a, axis=1)
b

array([[[1, 2]],

       [[3, 5]]])

You can also stack two existing arrays, both vertically and horizontally. Let’s say you have two arrays, a1 and a2:

In [116]:

a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])
# You can stack them vertically with vstack:

print(np.vstack((a1, a2)))

# Or stack them horizontally with hstack:

print(np.hstack((a1, a2)))


[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


You can split an array into several smaller arrays using hsplit. You can specify either the number of equally shaped arrays to return or the columns after which the division should occur.

In [117]:

# Let’s say you have this array:

x = np.arange(1, 25).reshape(2, 12)

# If you wanted to split this array into three equally shaped arrays, you would run:

print(np.hsplit(x, 3))

# If you wanted to split your array after the third and fourth column, you’d run:

print(np.hsplit(x, (3, 4)))
  

[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


## Data Operations and Statistics

In [119]:
data = np.array([1.0, 2.0])
data

array([1., 2.])

In [120]:
print(data.max())
print(data.min())
print(data.sum())

2.0
1.0
3.0


## Accessing or Changing Specific Elements, rows,columns,etc

In [37]:
arr=np.array([[1,2,3,4],[7,8,9,0]])
arr


array([[1, 2, 3, 4],
       [7, 8, 9, 0]])

In [38]:
#Get SPecific element
arr[1,]

2

In [39]:
arr[1,3]

0

In [40]:
#get row
arr[0,:]

array([1, 2, 3, 4])

In [41]:
#Get col
arr[:,0]

array([1, 7])

In [44]:
# Geting fancy [start,start:end:step]
arr[0,1:-2:1]

array([2])

In [45]:
arr[1,3]=90

In [46]:
arr

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 90]])

In [48]:
arr[:,2]=5

In [49]:
arr

array([[ 1,  2,  5,  4],
       [ 7,  8,  5, 90]])

In [51]:
d=np.array([[1,3,5],[2,4,6],[9,0,89]])

In [54]:
d.shape


(3, 3)

In [123]:
# You can transpose your array with arr.transpose().

arr.transpose()

array([[ 1,  7],
       [ 2,  8],
       [ 5,  5],
       [ 4, 90]])

Reversing a 2D array

A 2D array works much the same way.

In [124]:
# If you start with this array:

arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
# You can reverse the content in all of the rows and all of the columns with:

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

# You can easily reverse only the rows with:

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

# Or reverse only the columns with:

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

# You can also reverse the contents of only one column or row. For example, you can reverse the contents of the row at index position 1 (the second row):

arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

# You can also reverse the column at index position 1 (the second column):

arr_2d[:,1] = np.flip(arr_2d[:,1])
print(arr_2d)


[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]
[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## Intializing Different Types of Arrays

In [57]:
# All 0s
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [58]:
# All ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [60]:
# Other no
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [62]:
# Any other full_like
np.full_like(a,4)

array([4, 4, 4], dtype=int16)

In [63]:
# Matrix of random numbers
np.random.rand(4,2)

array([[0.83022287, 0.58024827],
       [0.89093331, 0.42848153],
       [0.4092338 , 0.925796  ],
       [0.48050571, 0.44264485]])

In [64]:
np.random.random_sample(a.shape)

array([0.72249113, 0.71345514, 0.8727131 ])

In [121]:
# uniques
unique_values = np.unique(a)
print(unique_values)

[1 2 3 5]


In [67]:
#Random Integer
np.random.randint(9,size=(2,3))

array([[1, 7, 2],
       [1, 0, 8]])

In [68]:
#Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [69]:
#reperat an array
r1=np.repeat(arr,3,axis=0)
r1

array([[ 1,  2,  5,  4],
       [ 1,  2,  5,  4],
       [ 1,  2,  5,  4],
       [ 7,  8,  5, 90],
       [ 7,  8,  5, 90],
       [ 7,  8,  5, 90]])

In [72]:
output=np.ones((5,5))
output

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [76]:
z=np.zeros((3,3))
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [77]:
z[1,1]=9

In [78]:
z

array([[0., 0., 0.],
       [0., 9., 0.],
       [0., 0., 0.]])

In [79]:
output[1:4,1:4]=z
output

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 9., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### Be careful while copying

In [80]:
f=a.copy()
# Creates a new copy instead of pointing to the same value
f

array([1, 2, 3], dtype=int16)

## Math Utitlies

In [81]:
m=np.array([1,2,4])
# Element wise addition, sub, mul
m+2

array([3, 4, 6])

In [82]:
m-1

array([0, 1, 3])

In [83]:
m*2

array([2, 4, 8])

In [84]:
m/4

array([0.25, 0.5 , 1.  ])

In [86]:
n=np.array([3,6,9])
m+n

array([ 4,  8, 13])

In [87]:
m**n

array([     1,     64, 262144])

In [88]:
#Take the sin
np.sin(n)

array([ 0.14112001, -0.2794155 ,  0.41211849])

In [98]:
np.cos(m)

array([ 0.54030231, -0.41614684, -0.65364362])

In [ ]:
# For a lot more (https://docs.scipy.org/doc/numpy/reference/routines.math.html)

## Linear Algebra

In [94]:
p=np.ones((2,3))
print(p)
q=np.full((3,2),2)
q

[[1. 1. 1.]
 [1. 1. 1.]]


array([[2, 2],
       [2, 2],
       [2, 2]])

In [96]:
# Matrix Multiplication
np.matmul(p,q)

array([[6., 6.],
       [6., 6.]])

In [97]:
# Determiniant of matrix
c=np.identity(2)
np.linalg.det(c)


1.0

Reference docs (https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)

Determinant
Trace
Singular Vector Decomposition
Eigenvalues
Matrix Norm
Inverse
Etc...

In [100]:
# Solve the system of equations x0 + 2 * x1 = 1 and 3 * x0 + 5 * x1 = 2:

a = np.array([[1, 2], [3, 5]])
b = np.array([1, 2])
x = np.linalg.solve(a, b)
x


array([-1.,  1.])

## Load from a file

In [133]:
nm=np.genfromtxt('data.txt',delimiter=',').astype('int16') # converts to int16 too

## Boolean Masking and Advanced Indexing

In [134]:
nm>50

array([False, False, False, False, False,  True, False])

In [135]:
nm[nm>50]

array([90], dtype=int16)

In [138]:
# you can index with a list in numy
po=np.array([23,56,78,0,90,45,1])

In [140]:
po[[1,2,3]]

array([56, 78,  0])