In [1]:
from keras.datasets import reuters
from keras import Sequential
from keras.layers import SimpleRNN,Flatten,Dense,Embedding
from keras.utils import pad_sequences

In [2]:
(X_train,y_train),(X_test,y_test)=reuters.load_data()

In [3]:
X_train.shape

(8982,)

In [4]:
len(X_train[2])

139

In [5]:
y_test[:5]

array([ 3, 10,  1,  4,  4], dtype=int64)

In [6]:
import numpy as np
X_train=pad_sequences(X_train,padding="post",maxlen=150)
X_test=pad_sequences(X_test,padding="post",maxlen=150)
y_train=np.asarray(y_train).astype('float32').reshape((-1,1))
y_test=np.asarray(y_test).astype('float32').reshape((-1,1))

In [7]:
X_train[0].shape

(150,)

In [8]:
model=Sequential()

In [9]:
model.add(SimpleRNN(32,input_shape=(100,1),return_sequences="False"))
model.add(Dense(1,activation="sigmoid"))
model.summary()


c:\Users\anany\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 100, 32)        │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 100, 1)         │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,121 (4.38 KB)

 Trainable params: 1,121 (4.38 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X_train,y_train,epochs=10,verbose='1')

Epoch 1/10
Epoch 2/10
Epoch 3/10
Epoch 4/10
Epoch 5/10
Epoch 6/10
Epoch 7/10
Epoch 8/10
Epoch 9/10
Epoch 10/10


# Structure of simple RNN

In [11]:
m2=Sequential()
m2.add(SimpleRNN(5,input_shape=(5,1),activation="linear"))
m2.add(Dense(5,activation='sigmoid'))
m2.compile(loss="mean_squared_error",optimizer="adam")
m2.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 5)              │            35 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 5)              │            30 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 65 (260.00 B)

 Trainable params: 65 (260.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
m2.get_weights()

[array([[-0.57633686,  0.5012231 ,  0.3990705 , -0.93216133,  0.3897636 ]],
       dtype=float32),
 array([[ 0.82839894,  0.04719295, -0.5580034 ,  0.00154728, -0.01256317],
        [ 0.05544025,  0.61207104,  0.12367596, -0.68138045,  0.37778336],
        [-0.4810608 ,  0.31445345, -0.6939391 ,  0.29412833,  0.31880492],
        [-0.13687979, -0.71937656, -0.27377352, -0.50184005,  0.37008902],
        [ 0.24602032, -0.08220797,  0.34180844,  0.44425595,  0.7864601 ]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32),
 array([[-0.39596733, -0.6819412 ,  0.02342921, -0.76399046,  0.73646355],
        [-0.15378231, -0.03910506, -0.27569008, -0.43810147,  0.26604414],
        [ 0.02497679,  0.05344367, -0.17289042,  0.45781553, -0.4970434 ],
        [-0.27950978,  0.45922983, -0.55209744,  0.10722828,  0.02238321],
        [-0.05374044,  0.26313126, -0.5007519 , -0.48479903,  0.21418524]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

# One to One RNN

In [14]:
m3=Sequential()
m3.add(SimpleRNN(4,input_shape=(4,1),activation="linear"))
m3.add(Dense(5,activation='sigmoid'))
m3.compile(loss="mean_squared_error",optimizer="adam")
m3.get_weights()

c:\Users\anany\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


[array([[-0.11573344, -0.25234783, -0.90067196,  0.6452527 ]],
       dtype=float32),
 array([[-0.08242679,  0.31004786, -0.7411451 ,  0.589729  ],
        [ 0.30373797,  0.5914444 ,  0.5841018 ,  0.46557683],
        [ 0.36914885, -0.7323829 ,  0.10070674,  0.5632074 ],
        [-0.8744589 , -0.13296261,  0.3152575 ,  0.3438828 ]],
       dtype=float32),
 array([0., 0., 0., 0.], dtype=float32),
 array([[-0.14926732,  0.49217808,  0.1580959 ,  0.6617619 ,  0.57049334],
        [ 0.06782234, -0.67291987, -0.47554794, -0.75421786, -0.53145367],
        [ 0.37967336,  0.62907577,  0.26920557, -0.7022771 ,  0.7108941 ],
        [-0.7770775 ,  0.21747684, -0.74488276, -0.05010033, -0.30136335]],
       dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [16]:
# get weights from input to hidden layer
print(m3.get_weights()[0])
# get weights from hidden to hidden layer
print(m3.get_weights()[1])
# bias of hidden layer
print(m3.get_weights()[2])
# weights from hidden to output layer
print(m3.get_weights()[3])
# bias of output layer
print(m3.get_weights()[4])


[[-0.11573344 -0.25234783 -0.90067196  0.6452527 ]]
[[-0.08242679  0.31004786 -0.7411451   0.589729  ]
 [ 0.30373797  0.5914444   0.5841018   0.46557683]
 [ 0.36914885 -0.7323829   0.10070674  0.5632074 ]
 [-0.8744589  -0.13296261  0.3152575   0.3438828 ]]
[0. 0. 0. 0.]
[[-0.14926732  0.49217808  0.1580959   0.6617619   0.57049334]
 [ 0.06782234 -0.67291987 -0.47554794 -0.75421786 -0.53145367]
 [ 0.37967336  0.62907577  0.26920557 -0.7022771   0.7108941 ]
 [-0.7770775   0.21747684 -0.74488276 -0.05010033 -0.30136335]]
[0. 0. 0. 0. 0.]


# One to Many RNN

In [17]:
# One to Many RNN

m4=Sequential()
m4.add(SimpleRNN(4,input_shape=(4,1),return_sequences=True,activation="linear"))
m4.add(Dense(4,activation='sigmoid'))
m4.compile(loss="mean_squared_error",optimizer="adam")
m4.summary()

c:\Users\anany\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_4 (SimpleRNN)        │ (None, 4, 4)           │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 4, 4)           │            20 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

# Many to One RNN

In [18]:
m5=Sequential()
m5.add(SimpleRNN(4,input_shape=(4,1),return_sequences=True,activation="linear"))
m5.add(Dense(4,activation='sigmoid'))
m5.compile(loss="mean_squared_error",optimizer="adam")

c:\Users\anany\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [19]:
m5.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_5 (SimpleRNN)        │ (None, 4, 4)           │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 4, 4)           │            20 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)

# Many to Many RNN

In [20]:
m6=Sequential()
m6.add(SimpleRNN(4,input_shape=(4,1),return_sequences=True,activation="linear"))
m6.add(Dense(4,activation='sigmoid'))
m6.compile(loss="mean_squared_error",optimizer="adam")
m6.summary()


c:\Users\anany\AppData\Local\Programs\Python\Python311\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_6 (SimpleRNN)        │ (None, 4, 4)           │            24 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 4, 4)           │            20 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 44 (176.00 B)

 Trainable params: 44 (176.00 B)

 Non-trainable params: 0 (0.00 B)