In [1]:
# Tensor flow relives us from creating linking between nodes, it does it for us cuz manually we would create a lot of mistakes.
# All NN can be made from scratch and all lib like TF will have its own Data Structure and have operations on it.


# Introduction to Tensors, TensorFlow, and Keras

## 1. Tensors

### 1.1 What is a Tensor?

A tensor is a multi-dimensional array used to represent data in a structured format. Tensors are fundamental to many machine learning and deep learning frameworks, as they enable efficient mathematical operations and data manipulation.

- **0D Tensor (Scalar)**: A single value. Example: `5`
- **1D Tensor (Vector)**: A one-dimensional array of values. Example: `[1, 2, 3]`
- **2D Tensor (Matrix)**: A two-dimensional array of values arranged in rows and columns. Example: `[[1, 2], [3, 4]]`
- **3D Tensor**: A three-dimensional array. Example: `[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]`
- **4D Tensor**: A four-dimensional array. Example: `[[[[1, 2], [3, 4]], [[5, 6], [7, 8]]]]`
- **5D Tensor**: A five-dimensional array. Example: `[[[[[1, 2]]]]]`

### 1.2 Tensor Components

- **Shape**: Describes the dimensions of the tensor. For example, a tensor with shape `(3, 4)` has 3 rows and 4 columns.
- **Data Type**: Specifies the type of data stored in the tensor (e.g., `int32`, `float32`).
- **Rank**: The number of dimensions a tensor has. For example, a matrix has a rank of 2.

### 1.3 Tensor Operations

- **Addition and Subtraction**: Element-wise operations.
- **Multiplication**: Can be element-wise or matrix multiplication.
- **Reshaping**: Changing the shape of a tensor without altering its data.
- **Slicing and Indexing**: Extracting specific parts of a tensor.
- **Broadcasting**: Expanding the shape of a tensor to match another tensor for element-wise operations.

### 1.4 Broadcasting

Broadcasting is a method of expanding tensors with smaller shapes to match tensors with larger shapes for element-wise operations. The broadcasting rules are:

1. **Align Shapes**: Compare shapes from the rightmost dimension.
2. **Compatibility Check**: Dimensions must be either equal or one of them must be 1.
3. **Expand Dimensions**: Pad dimensions with ones where necessary.

## 2. TensorFlow

### 2.1 What is TensorFlow?

TensorFlow is an open-source machine learning library developed by Google. It provides tools for building and training machine learning models, particularly neural networks. TensorFlow supports both CPU and GPU computations and is designed to facilitate deep learning research and production.

### 2.2 Key Features

- **Flexible and Efficient**: Allows for complex computations and efficient execution on various hardware.
- **Keras Integration**: Provides high-level APIs for easier model building.
- **Ecosystem**: Includes tools for data loading, preprocessing, and visualization (e.g., TensorBoard).

### 2.3 TensorFlow Components

- **Tensors**: The core data structure used for computations.
- **Graphs**: Computational graphs represent the structure of computations in TensorFlow.
- **Sessions**: Execute the computational graphs in TensorFlow.
- **Layers**: Building blocks for constructing neural networks.

### 2.4 Basic Operations

```python
import tensorflow as tf

# Create tensors
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

# Add tensors
c = tf.add(a, b)

print(c)


In [2]:
import tensorflow as tf

In [11]:
# Creating a scalar
scalar=tf.constant(3)
# printing
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=3>


The expression <tf.Tensor: shape=(), dtype=int32, numpy=3> describes a scalar tensor in TensorFlow. Here's what each part means:

<tf.Tensor: This indicates that the object is a TensorFlow tensor.

shape=(), The shape () signifies that the tensor is a scalar, meaning it has no dimensions (0D tensor). Scalars contain a single value, unlike vectors or matrices, which have one or more dimensions.

dtype=int32, This shows the data type of the tensor's single value. In this case, int32 indicates that the value is a 32-bit integer.

numpy=3> This represents the value stored in the tensor, shown as a NumPy value. Here, the value is 3.


In [6]:
vector=tf.constant([1,2,3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])>

The expression <tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3])> is a representation of a tensor in TensorFlow. Here's what each part means:

<tf.Tensor: This indicates that the object is a TensorFlow tensor.

shape=(3,), This specifies the shape of the tensor. The shape (3,) means that the tensor is a 1-dimensional array (or vector) with 3 elements.

dtype=int32, This indicates the data type of the elements within the tensor. In this case, int32 means that the elements are 32-bit integers.

numpy=array([1, 2, 3])> This shows the contents of the tensor as a NumPy array, which is [1, 2, 3]. TensorFlow tensors can be converted to NumPy arrays, and this field helps visualize the data stored in the tensor.

In [7]:
matrix=tf.constant([[1,2],[4,5],[5,6]])
matrix

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [4, 5],
       [5, 6]])>

The expression <tf.Tensor: shape=(3, 2), dtype=int32, numpy=array([[1, 2], [4, 5], [5, 6]])> describes a 2D tensor in TensorFlow. Here's what each part means:

<tf.Tensor: This indicates that the object is a TensorFlow tensor.

shape=(3, 2), The shape (3, 2) specifies that the tensor has 2 dimensions: 3 rows and 2 columns. In other words, it's a matrix with 3 rows and 2 columns.

dtype=int32, This shows that the elements of the tensor are 32-bit integers (int32).

numpy=array([[1, 2], [4, 5], [5, 6]])> This represents the actual data in the tensor as a NumPy array. The values in this tensor are:

In [15]:
three_d = tf.constant([
    [[1, 2], [4, 5], [5, 6]],
    [[1, 2], [4, 5], [5, 6]],
    [[1, 2], [4, 5], [5, 6]]
])

three_d

<tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [4, 5],
        [5, 6]],

       [[1, 2],
        [4, 5],
        [5, 6]],

       [[1, 2],
        [4, 5],
        [5, 6]]])>

The expression <tf.Tensor: shape=(3, 3, 2), dtype=int32, numpy=array([[[1, 2], [4, 5], [5, 6]], [[1, 2], [4, 5], [5, 6]], [[1, 2], [4, 5], [5, 6]]])> describes a 3D tensor in TensorFlow. Here’s what each part means:

Breakdown of the Tensor
<tf.Tensor: This indicates that the object is a TensorFlow tensor.

shape=(3, 3, 2), This shows that the tensor has 3 dimensions:

The first dimension has 3 elements (3 matrices).
The second dimension also has 3 elements (3 rows in each matrix).
The third dimension has 2 elements (2 columns in each row).
dtype=int32, This indicates that the data type of the elements in the tensor is 32-bit integers (int32).

numpy=array([[[1, 2], [4, 5], [5, 6]], [[1, 2], [4, 5], [5, 6]], [[1, 2], [4, 5], [5, 6]]])> This represents the tensor’s data in a NumPy array format. The tensor contains the following values:

In [16]:
# Creating a 4D tensor
four_d = tf.constant([
    [
        [[1, 2], [3, 4], [5, 6]],  # First 3x2 matrix
        [[7, 8], [9, 10], [11, 12]]  # Second 3x2 matrix
    ],
    [
        [[13, 14], [15, 16], [17, 18]],  # Third 3x2 matrix
        [[19, 20], [21, 22], [23, 24]]   # Fourth 3x2 matrix
    ]
])

four_d


<tf.Tensor: shape=(2, 2, 3, 2), dtype=int32, numpy=
array([[[[ 1,  2],
         [ 3,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]],


       [[[13, 14],
         [15, 16],
         [17, 18]],

        [[19, 20],
         [21, 22],
         [23, 24]]]])>

In [17]:
# Creating a 5D tensor with a single element
five_d = tf.constant([[[[[42]]]]])
five_d

<tf.Tensor: shape=(1, 1, 1, 1, 1), dtype=int32, numpy=array([[[[[42]]]]])>

In [19]:
result=tf.add(vector,1)
print(vector)
print(result)  # Broadcasting is done where another tensor is created and operation is done on it.
# It does all the shaping and all if the shapes of two tensor are different

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([2 3 4], shape=(3,), dtype=int32)


In [20]:
multiply=scalar*matrix
print(matrix)
print(multiply)

tf.Tensor(
[[1 2]
 [4 5]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  6]
 [12 15]
 [15 18]], shape=(3, 2), dtype=int32)


In [22]:
multiply_5d=matrix*five_d
print(matrix)
print(multiply)

tf.Tensor(
[[1 2]
 [4 5]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 3  6]
 [12 15]
 [15 18]], shape=(3, 2), dtype=int32)


# Broadcasting Rules in TensorFlow

Broadcasting is a technique used in TensorFlow (and NumPy) that allows for element-wise operations on tensors of different shapes. This is done by automatically expanding the smaller tensor's shape to match the shape of the larger tensor. Broadcasting follows specific rules to ensure compatibility. Below is an explanation of these rules.

## Broadcasting Rules

1. **Align Shapes**:
   - Tensor shapes are compared from right to left.
   - If the shapes differ, TensorFlow expands the smaller shape along its dimensions to match the larger shape.

2. **Compatibility Check**:
   - Two dimensions are compatible if they are equal or one of them is 1.
   - If dimensions are different and neither is 1, broadcasting cannot be performed, and an error will be raised.

3. **Expand Dimensions**:
   - If a tensor has fewer dimensions, its shape is padded with ones on the left until the shapes have the same number of dimensions.
   - The tensor is then broadcasted by repeating its elements along the dimensions where it is 1.

## Examples

### Example 1: Basic Broadcasting

**Tensors**:
- `A` with shape `(3, 4)`
- `B` with shape `(1, 4)`

**Operation**: Addition

**Result Shape**: `(3, 4)`

**Explanation**: Tensor `B` is broadcasted to shape `(3, 4)` by repeating its values along the first dimension.

```python
import tensorflow as tf

A = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
B = tf.constant([[1, 2, 3, 4]])

result = A + B
print(result)


In [26]:

# Define a 2D tensor
A = tf.constant([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

# Define a 5D tensor
B = tf.constant([[[[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]]]]])




In [28]:

# Perform element-wise multiplication
ans = A[:, :, tf.newaxis] * B

# Displaying the result
print(ans)


tf.Tensor(
[[[[[  1   2   3   4   5]
    [ 12  14  16  18  20]
    [ 33  36  39  42  45]
    [ 64  68  72  76  80]]

   [[  5  10  15  20  25]
    [ 36  42  48  54  60]
    [ 77  84  91  98 105]
    [128 136 144 152 160]]

   [[  9  18  27  36  45]
    [ 60  70  80  90 100]
    [121 132 143 154 165]
    [192 204 216 228 240]]]]], shape=(1, 1, 3, 4, 5), dtype=int32)


# TensorFlow Operations

## 1. Tensor Creation

### 1.1 Creating Constants

```python
import tensorflow as tf

# Scalar
scalar = tf.constant(5)
print("Scalar:", scalar)

# Vector
vector = tf.constant([1, 2, 3, 4])
print("Vector:", vector)

# Matrix
matrix = tf.constant([[1, 2], [3, 4]])
print("Matrix:\n", matrix)

# 3D Tensor
tensor3d = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("3D Tensor:\n", tensor3d)


In [29]:
# Create a variable
var = tf.Variable([1, 2, 3])
print("Variable:", var)

# Initialize variables
init = tf.compat.v1.global_variables_initializer()


Variable: <tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3])>

